project:
  type: website

execute:
  freeze: true

website:
  title: "Shon Czinner's Blog"

  description: "Shon Czinner's blog about AI, statistics, quantitative finance, economics, and more"

  site-url: "https://shonczinner.github.io/"

  favicon: favicon.png

  open-graph:
    site-name: "Shon Czinner's Blog"
    locale: en_CA

  twitter-card: true

  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shonczinner
      - icon: linkedin
        href: https://www.linkedin.com/in/shon-czinner-14a258140/
      - icon: rss
        href: index.xml

  google-analytics:
    tracking-id: "G-44Q7K7T86R"
    anonymize-ip: true

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    include-in-header:
      - includes/schema.html
      - includes/google-verification.html

csl: https://www.zotero.org/styles/ieee
citeproc: true